### ISSUE TITLE
rutorrent crashing rtorrent

### ISSUE THREAD

**Issue by runaroundhome** [romancin/rutorrent-flood-docker#14]
Anyone else having issues where when you get about 1,300 torrents going that when you try load rutorrent's webUI it takes ages, then finally loads to tell you rtorrent isn't open. Then I check the container and yes, it's no longer running.

Tried a few times, happens each time I restart the container and try refresh the rutorrent tab. 
The flood interface doesn't seem to have any issues loading it up, it just stops working shortly after trying to load rutorrent since rtorrent has been crashed.

**Comment by romancin** [comment]
Right now I have 2500 torrents seeding with the same problem than you, when I restart container, rtorrent hang after a short time because os flood polling it too frequently, could you please test to comment the line:
exec /usr/flood/server/bin/www
In /etc/services.d/flood/run file inside container, restart container and tell me if rutorrent works?

**Comment by runaroundhome** [comment]
I commented out the exec flood line in the run file and the same thing is still happening.
When I try to load rutorrent I get `Bad response from server: (500 [error,list]) Link to XMLRPC failed. May be, rTorrent is down?`.
While I can see rtorrent was running inside the container via top before trying to open the rutorrent web interface.

**Comment by romancin** [comment]
Great to hear that. If problems appear again, come back and we will see what is happening.
